polling/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("polls.urls"))
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path("", views.index, name="Home"),
    path("polls/", views.polls, name="Polls"),
    path('polls/<int:question_id>/', views.details, name='details'),
    path('polls/<int:question_id>/results/', views.result, name='result'),
    path('polls/<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=255)
	pub_date = models.DateTimeField()
	def __str__(self):
		return self.question_text
		
class Choices(models.Model):
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=255)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render
from .models import Question,Choices
from django.shortcuts import get_object_or_404
from django.shortcuts import get_list_or_404
# Create your views here.
def index(request):
	
	return render(request,"index.html" ,{})
	
def polls(request):
	polled = Question.objects.order_by("id")
	return render(request,"polls.html" , {"poller":polled})
	

def details(request , question_id):
	polled = get_object_or_404(Question , pk=question_id)
	choiceed = get_list_or_404(Choices, question=polled)	
	content_dict = {"poller":polled,"choice":choiceed}
	return render(request , "details.html" , context=content_dict)
	
def result(request,question_id):
	polled = get_object_or_404(Question , pk=question_id)
	choiceed = get_list_or_404(Choices, question=polled)	
	content_dict = {"poller":polled,"choice":choiceed}

	return render(request ,"result.html" , context=content_dict)

def vote(request,question_id):
	polled = get_object_or_404(Question , pk=question_id)
	choiceed = get_list_or_404(Choices, question=polled)	
	content_dict = {"poller":polled,"choices":choiceed}
	
	if request.method =="POST":
		selected_choice = Choices.objects.get(pk=request.POST['choice'])
		selected_choice.votes += 1
		selected_choice.save()
   
	return render(request , "vote.html" , context=content_dict)
	

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <!--  -- <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title><!- -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        a:link{color:white;}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>
    
    
    
    <div class="container">
        {% block body_block %}
        {% endblock%}
    </div>
    
    
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Page title</title>
</head>
<body>
    {%if poller %}
    <h2>{{poller.question_text}}</h2>
    {% for i in choice%}
    
    
        <li>{{i.choice_text}}</li>
    
    {%endfor%}
    <button type="button" class="btn btn-outline-primary"><a href="{%url 'polls:vote' question_id=poller.id %}">Vote Now</a></button>
    <button type="button" class="btn btn-outline-primary"><a href="{%url 'polls:Polls' %}">Choose Another Question</a></button>
     {%endif%}
</body>
</html>
{% endblock%}

templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Home Page</title>
</head>
<body>
    <h1>Want to Vote too?</h1>
    <h4>Just Click Below to See all Questions for voting</h4>
    <button type="button" class="btn btn-primary"><a href="{%url 'polls:Polls' %}">Click Here</a></button>
</body>
</html>
{% endblock%}

templates/polls.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8" >
     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Voting Site</title>
</head>
<body>
    <h1>All Available Question For Voting are below:</h1>
    {%if poller %}
    {% for p in poller %}
       
      <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ p.question_text }}</h5>

    <a href="{%url 'polls:details' question_id=p.id %}" class="card-link">Vote Now</a>

  </div>
</div>
    {% endfor %}
    {%endif%}
</body>
</html>
{% endblock%}

templates/result.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Page title</title>
</head>
<body>
    {%if poller %}
    <h2>{{poller.question_text}}</h2>
    {% for i in choice%}
    
    
        <li>{{i.choice_text}}   Total Votes:{{i.votes}}</li>
    
    {%endfor%}
    <button type="button" class="btn btn-outline-primary"><a href="{%url 'polls:vote' question_id=poller.id %}">Vote Again</a></button>
    <button type="button" class="btn btn-outline-primary"><a href="{%url 'polls:Polls' %}"> Chose Another Question</a></button>
     {%endif%}
</body>
</html>
{% endblock%}

templates/vote.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Vote Here</title>
</head>
<body>
    <h2>Vote Now</h2>
    {%if poller %}
    <h2>{{poller.question_text}}</h2>
    
   
    <form method="post">
    {% csrf_token %}
    {% for choice in choices %}
    <div class="form-check">
        <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
    
    <button type="button" class="btn btn-outline-primary"><a href="{%url 'polls:result' question_id=poller.id %}">See Results</a></button>
    <button type="button" class="btn btn-outline-primary"><a href="{%url 'polls:Polls' %}">Choose Another Question</a></button>
     {%endif%}
</body>
</html>
{% endblock%}